### PR TITLE
Add gnome-control-center & gnome-settings-daemon

### PR DESCRIPTION
**Pull request by Woomeeme**

### CODE REVIEW

**Review by UTsweetyfish — COMMENTED** [review]
Why?

**Comment by Woomeeme** [comment]
Needed by mutter (notice on the OBS)

**Comment by Woomeeme** [comment]
> Why?

Needed by mutter (notice on the OBS)

**Comment by Woomeeme** [comment]
@UTsweetyfish

**Review by UTsweetyfish — APPROVED** [review]

**Pull request merged**
