### PR TITLE
add rust-strsim

### PR DESCRIPTION
**Pull request by liushanyang12138**
[feat: Implementations of string similarity metrics - Rust source code](https://github.com/deepin-community/Repository-Manager/pull/61/commits/ce745c6657079382e2623ee7731da3d38556ce69) 

 Includes Hamming, Levenshtein, OSA, Damerau-Levenshtein, Jaro, Jaro-Winkler,
 and SÃ¸rensen-Dice.
 .
 This package contains the source for the Rust strsim crate, packaged by
 debcargo for use with cargo and dh-cargo.

Log: Implementations of string similarity metrics - Rust source code
Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/56
Task: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/5
Influence: Implementations of string similarity metrics - Rust source code

### CODE REVIEW

**Review by Rabenda — APPROVED** [review]

**Comment by Rabenda** [comment]
无理由直接修改回来`title`

**Review by Rabenda — CHANGES_REQUESTED** [review]
明确PR标题意义

**Comment by liushanyang12138** [comment]
> 增加软件就写增加软件的名字 不要改成无意义的`Update repo.yml`

打错了，已修改

**Comment by liushanyang12138** [comment]
> 明确PR标题意义

已明确，请通过QaQ

**Comment by liushanyang12138** [comment]
rust-strsim issue:https://github.com/deepin-community/sig-deepin-sysdev-team/issues/56

**Review by chenchongbiao — APPROVED** [review]

**Pull request merged**
