### PR TITLE
add dummyapp-wpsoffice

### PR DESCRIPTION
**Pull request by RigoLigoRLC**

### CODE REVIEW

**Comment by UTsweetyfish** [comment]
What's this?

**Comment by BLumia** [comment]
> What's this?

A dummy/virtual entry which will be visible in DDE (launchpad, file manager) which represents a package (WPS in this case) that is not currently installed but allows user install it with an interactive manner.

**Comment by UTsweetyfish** [comment]
以后会不会有除了 wps 以外的其他这种需求（

**Comment by BLumia** [comment]
> 以后会不会有除了 wps 以外的其他应用的这种需求（

可能会有

**Pull request closed without merging**
